### ISSUE TITLE
Error when I want to run demo

### ISSUE THREAD

**Issue by HDFengChina** [tum-pbs/PhiFlow#142]
I copied the demos like rotating bar and run them based on different version of PhiFlow. 

An error AttributeError: 'NoneType' object has no attribute '__file__' always occured. 

Do you know the reason?

Thank you.

**Comment by HDFengChina** [comment]
Error occured on "for _ in view('vorticity,velocity,pressure', namespace=globals()).range():"

**Comment by holl-** [comment]
What version of PhiFlow are you on?
You can check using `import phi; phi.verify()`.

**Comment by HDFengChina** [comment]
> What version of PhiFlow are you on? You can check using `import phi; phi.verify()`.
> 
> Also, could you send the full error stack trace?

Thanks for your reply. It works in the version 2.5.1. It is a very useful tool for me.

**Comment by holl-** [comment]
Glad to hear!
So the error only occurred in an older version and is gone in 2.5.1, right?

**Comment by HDFengChina** [comment]
> Glad to hear! So the error only occurred in an older version and is gone in 2.5.1, right?

Sure. 

But it is difficult to determine whether it is the issue on my environmental or the phiflow. Anyway, the problem has been resolved.

**Comment by HDFengChina** [comment]
> Glad to hear! So the error only occurred in an older version and is gone in 2.5.1, right?

One more question. 

Where is the Reynolds number located when solving the PDE? 
Maybe it is calculated by density, viscosity, inflow velocity. I think by changing the inflow velocity I can change the Reynolds number. But I did not find its definition in the code.

Thanks for your help.

**Comment by holl-** [comment]
The Reynolds number can be computed from your viscosity, characteristic velocity and characterstic length scale. So for a fixed setup, you can vary the viscosity (diffusivity) to affect the Reynolds number.
See [this demo](https://tum-pbs.github.io/PhiFlow/Fluid_Simulation.html) for a fluid with diffusion.

**Comment by HDFengChina** [comment]
> The Reynolds number can be computed from your viscosity, characteristic velocity and characterstic length scale. So for a fixed setup, you can vary the viscosity (diffusivity) to affect the Reynolds number. See [this demo](https://tum-pbs.github.io/PhiFlow/Fluid_Simulation.html) for a fluid with diffusion.

Thanks for your answer, It can solve my problem.

**Comment by holl-** [comment]
Perfect!
